# .travis.yml
os: linux
sudo: required
language: php
services:
  - mysql
dist: trusty
addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
cache:
  directories:
    - $HOME/.composer/cache
    - ${TRAVIS_BUILD_DIR}/travis/extension-cache
    - vendor
env:
  - DB=mysql
matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: LARAVEL='5.5.*' TESTBENCH='3.5.*' COMPOSER_FLAGS='--prefer-lowest' DB=mysql
  allow_failures:
    - php: 7.2
      env: LARAVEL='5.5.*' TESTBENCH='3.5.*' COMPOSER_FLAGS='--prefer-lowest'

before_script:
  - mysql -u root -e 'CREATE USER IF NOT EXISTS root@localhost; GRANT ALL ON *.* TO root@localhost;'
  - travis_retry composer self-update --stable -n

install:
  - travis_retry composer update --no-interaction --no-plugins --no-suggest --prefer-source ${COMPOSER_FLAGS}

script:
  - vendor/bin/phpunit

notifications:
  email: false
