# .travis.yml
os: linux
sudo: required
language: php
cache:
  directories:
    - $HOME/.composer/cache
    - ${TRAVIS_BUILD_DIR}/travis/extension-cache
    - vendor

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: LARAVEL='5.7.*' TESTBENCH='3.7.*'
    - php: 7.3
      env: LARAVEL='5.8.*' TESTBENCH='3.8.*'
    - php: 7.3
      env: LARAVEL='6.0.0' TESTBENCH='4.0.*'

before_script:
  - travis_retry composer self-update --stable -n
  - travis_retry composer require --no-interaction "laravel/framework:${LARAVEL}" "orchestra/testbench:${TESTBENCH}"

install:
  - travis_retry composer update --no-interaction --no-plugins --no-suggest --prefer-source ${COMPOSER_FLAGS}

script:
  - composer dump-autoload -o
  - composer test

notifications:
  email: false
