# .travis.yml
os: linux
sudo: required
language: php
cache:
  directories:
    - $HOME/.composer/cache
    - ${TRAVIS_BUILD_DIR}/travis/extension-cache
    - vendor

matrix:
  fast_finish: true
  include:
    - php: 7.3
      env: LARAVEL='5.7.*' TESTBENCH='3.8.*'
    - php: 7.3
      env: LARAVEL='5.8.*' TESTBENCH='3.8.*'

before_script:
  - travis_retry composer self-update --stable -n
  - travis_retry composer require --no-update --no-interaction "illuminate/support:${LARAVEL}" "orchestra/testbench:${TESTBENCH}"
  - travis_retry ./vendor/bin/upgrade-carbon

install:
  - travis_retry composer update --no-interaction --no-plugins --no-suggest --prefer-source ${COMPOSER_FLAGS}

script:
  - composer dump-autoload -o
  - composer test

notifications:
  email: false
